// The structure of the rules system (The System). Single source of truth for
// both the /system/ table of contents and the per-section stub pages.
//
// Each entry maps to a route /system/<slug>/. Entries with `stub: false` have
// their own hand-built route (e.g. Classes) and are not generated by the
// dynamic [section].astro stub route.

export type SystemStatus = 'live' | 'designed' | 'progress' | 'planned';

export interface SystemEntry {
  slug: string;
  title: string;
  blurb: string;
  status: SystemStatus;
  stub?: boolean; // default true
}

export interface SystemPart {
  part: string;
  items: SystemEntry[];
}

export const STATUS_LABEL: Record<SystemStatus, string> = {
  live: 'Live',
  designed: 'In design',
  progress: 'In progress',
  planned: 'Planned',
};

export const SYSTEM: SystemPart[] = [
  {
    part: 'I · Foundations',
    items: [
      { slug: 'introduction', title: 'Introduction & How to Play', blurb: 'What the game is, the d20 core it runs on, and the Ladders and Ranks every Ability is built from.', status: 'live' },
      { slug: 'character-creation', title: 'Character Creation', blurb: 'Advances (Major & Minor), Levels 0–11, and Milestone advancement.', status: 'live', stub: false },
      { slug: 'character-sheet', title: 'Character Sheet', blurb: 'A look at the digital character sheet — the example Soldier laid out across four pages.', status: 'live', stub: false },
      { slug: 'attributes', title: 'Attributes, Offences & Defences', blurb: 'The six Attributes, AC, and the Armoured / Unarmoured Defences.', status: 'live' },
      { slug: 'skills', title: 'Skills', blurb: 'The Skills of Avilund, each tied to an Attribute — with the Heal Skill in play.', status: 'live', stub: false },
      { slug: 'proficiencies', title: 'Proficiencies', blurb: 'Weapon groups (magic items included), armour, and how training in them is granted, advanced, and specialized.', status: 'live' },
    ],
  },
  {
    part: 'II · Classes & Abilities',
    items: [
      { slug: 'classes', title: 'Classes & Subclasses', blurb: 'Eleven vocations, each with three Subclasses. The Soldier is written up in full.', status: 'live', stub: false },
      { slug: 'abilities', title: 'Abilities', blurb: 'Ability Categories, and the chassis of eight dials each power is built from.', status: 'live', stub: false },
      { slug: 'feats', title: 'Feats', blurb: 'The specialist economy — conditional edges that reshape your Abilities.', status: 'progress' },
    ],
  },
  {
    part: 'III · Combat',
    items: [
      { slug: 'combat', title: 'Combat', blurb: 'The turn and its actions, attack resolution, and the rules for falling, dying, and recovery.', status: 'progress' },
      { slug: 'conditions', title: 'Conditions', blurb: 'The laddered Conditions — Ongoing Damage, Action Denial, Movement, Control, and the rest.', status: 'live' },
      { slug: 'light', title: 'Light & Darkness', blurb: 'The Ladder from Daylight down to the Void, what each rung costs you, and what can reach it.', status: 'live' },
    ],
  },
  {
    part: 'IV · Gear',
    items: [
      { slug: 'equipment', title: 'Equipment', blurb: 'Weapons, armour & shields, sundries, and coin.', status: 'live' },
    ],
  },
  {
    part: 'V · Magic',
    items: [
      { slug: 'magic', title: 'Magic', blurb: 'Spells found, not chosen — scrolls, spellbooks and rituals, and the Feats that wield magic items.', status: 'progress' },
    ],
  },
  {
    part: 'VI · The Game Master’s Section',
    items: [
      { slug: 'game-master', title: 'For the Game Master', blurb: 'Encounters, adversaries, and the secrets of running Avilund.', status: 'planned' },
    ],
  },
];

// Flattened entries with their part label attached — handy for stub generation.
export const SYSTEM_ENTRIES = SYSTEM.flatMap((p) =>
  p.items.map((item) => ({ ...item, part: p.part }))
);

// Previous / next section in reading order (for the chapter nav at the foot of
// each System page). Either may be undefined at the ends of the sequence.
export function systemNav(slug: string): {
  prev?: { slug: string; title: string };
  next?: { slug: string; title: string };
} {
  const i = SYSTEM_ENTRIES.findIndex((e) => e.slug === slug);
  if (i === -1) return {};
  const at = (n: number) =>
    SYSTEM_ENTRIES[n] ? { slug: SYSTEM_ENTRIES[n].slug, title: SYSTEM_ENTRIES[n].title } : undefined;
  return { prev: at(i - 1), next: at(i + 1) };
}
