// The structure of the rules system (The System). Single source of truth for
// both the /system/ table of contents and the per-section stub pages.
//
// Each entry maps to a route /system/<slug>/. Entries with `stub: false` have
// their own hand-built route (e.g. Classes) and are not generated by the
// dynamic [section].astro stub route.

export type SystemStatus = 'live' | 'designed' | 'progress' | 'planned';

export interface SystemEntry {
  slug: string;
  title: string;
  blurb: string;
  status: SystemStatus;
  stub?: boolean; // default true
}

export interface SystemPart {
  part: string;
  items: SystemEntry[];
}

export const STATUS_LABEL: Record<SystemStatus, string> = {
  live: 'Live',
  designed: 'In design',
  progress: 'In progress',
  planned: 'Planned',
};

export const SYSTEM: SystemPart[] = [
  {
    part: 'I · Foundations',
    items: [
      { slug: 'introduction', title: 'Introduction & How to Play', blurb: 'What the game is, and the d20 core it runs on.', status: 'planned' },
      { slug: 'character-creation', title: 'Character Creation', blurb: 'Advances (Major & Minor), levels 0–11, and milestone advancement.', status: 'live', stub: false },
      { slug: 'attributes', title: 'Attributes, Offenses & Defenses', blurb: 'The six attributes, AC, and the Armoured / Unarmoured defenses.', status: 'designed' },
      { slug: 'skills', title: 'Skills', blurb: 'The twenty-nine skills, each tied to an attribute.', status: 'designed' },
      { slug: 'proficiencies', title: 'Proficiencies', blurb: 'Weapon groups and armour, and how training in them works.', status: 'designed' },
    ],
  },
  {
    part: 'II · Classes & Abilities',
    items: [
      { slug: 'classes', title: 'Classes & Paths', blurb: 'Eleven vocations, each with three Paths. The Soldier is written up in full.', status: 'live', stub: false },
      { slug: 'abilities', title: 'Abilities', blurb: 'Ability Categories, and the chassis of eight dials each power is built from.', status: 'live', stub: false },
      { slug: 'conditions', title: 'Conditions', blurb: 'The laddered conditions — Daze, Control, Movement, Debuff, and the rest.', status: 'live' },
      { slug: 'feats', title: 'Feats', blurb: 'The specialist economy — conditional perks that reshape your abilities.', status: 'designed' },
    ],
  },
  {
    part: 'III · Gear & Combat',
    items: [
      { slug: 'equipment', title: 'Equipment', blurb: 'The weapon, armour, and gear lists.', status: 'progress' },
      { slug: 'combat', title: 'Combat', blurb: 'The turn, the action economy, attack resolution, range and cover.', status: 'designed' },
    ],
  },
  {
    part: 'IV · Magic',
    items: [
      { slug: 'magic', title: 'Magic', blurb: 'The arcane and occult arts of Avilund.', status: 'planned' },
    ],
  },
  {
    part: 'V · The Game Master’s Section',
    items: [
      { slug: 'game-master', title: 'For the Game Master', blurb: 'Encounters, adversaries, and the secrets of running Avilund.', status: 'planned' },
    ],
  },
];

// Flattened entries with their part label attached — handy for stub generation.
export const SYSTEM_ENTRIES = SYSTEM.flatMap((p) =>
  p.items.map((item) => ({ ...item, part: p.part }))
);

// Previous / next section in reading order (for the chapter nav at the foot of
// each System page). Either may be undefined at the ends of the sequence.
export function systemNav(slug: string): {
  prev?: { slug: string; title: string };
  next?: { slug: string; title: string };
} {
  const i = SYSTEM_ENTRIES.findIndex((e) => e.slug === slug);
  if (i === -1) return {};
  const at = (n: number) =>
    SYSTEM_ENTRIES[n] ? { slug: SYSTEM_ENTRIES[n].slug, title: SYSTEM_ENTRIES[n].title } : undefined;
  return { prev: at(i - 1), next: at(i + 1) };
}
